name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.2' 
      
      # Requied Poetry
      - name: Install Poetry
        run: pip3 install poetry

      # Install dependencies
      - name: Install dependencies
        run: poetry install

      # configuring API Token
      - name: Configure PyPI API
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      # Build the package
      - name: Build package
        run: poetry build

      # Upload the built package
      - name: Publish to PyPI
        run: poetry publish
